spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learningPlatform?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1305696249
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
knife4j:
  basic:
    enable: true